# Generated by Django 2.2.5 on 2019-09-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.AlterField(
            model_name='event',
            name='leader',
            field=models.CharField(max_length=20),
        ),
    ]
