# Generated by Django 2.2.5 on 2019-09-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190914_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
