# Generated by Django 2.2.5 on 2019-09-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190914_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
